Fix to run script

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -87,7 +87,7 @@ jobs:
         run: |
           curl -s https://test-id.a1ecbr0wn.workers.dev > test.ip
           curl -s https://ident.me > idm.ip
-          if ! cmp -zs test.ip idm.ip; then
-            echo "::error title=Build Failure::IP addresses do not match"
+          if ! cmp -s test.ip idm.ip; then
+            echo "::error title=Deploy Test Failure::IP addresses from test-id.a1ecbr0wn.workers.dev and ident.me do not match"
             exit 1
           fi
diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -88,7 +88,7 @@ jobs:
         run: |
           curl -s https://id.a1ecbr0wn.com > prod.ip
           curl -s https://ident.me > idm.ip
-          if ! cmp -zs prod.ip idm.ip; then
-            echo "::error title=Build Failure::IP addresses do not match"
+          if ! cmp -s prod.ip idm.ip; then
+          echo "::error title=Deploy Test Failure::IP addresses from id.a1ecbr0wn.com and ident.me do not match"
             exit 1
           fi
