Add a check to the release workflow to check that a release tag is singed, if not the build will failed

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -13,7 +13,7 @@ env:
 jobs:
   signed:
     name: Tag Signature Check
-    runs-on: ubuntu-latests
+    runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -21,10 +21,11 @@ jobs:
       - name: Check Tag is signed
         run: git tag -v ${{ github.ref_name }}
 
-      # Check the rust formatting
+  # Check the rust formatting
   format:
     name: Rust Format Check
     runs-on: ubuntu-latest
+    needs: [signed]
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -42,6 +43,7 @@ jobs:
   clippy:
     name: Rust Clippy Check
     runs-on: ubuntu-latest
+    needs: [signed]
     permissions:
       contents: read
       security-events: write
@@ -68,44 +70,44 @@ jobs:
           wait-for-processing: true
 
   # Deploy to the production environment
-  deploy:
-    name: Deploy to the Production Environment
-    runs-on: ubuntu-latest
-    needs: [signed, format, clippy]
+  # deploy:
+  #   name: Deploy to the Production Environment
+  #   runs-on: ubuntu-latest
+  #   needs: [format, clippy]
 
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
 
-      - name: Rust Toolchain setup
-        uses: dtolnay/rust-toolchain@stable
-        with:
-          target: wasm32-unknown-unknown
+  #     - name: Rust Toolchain setup
+  #       uses: dtolnay/rust-toolchain@stable
+  #       with:
+  #         target: wasm32-unknown-unknown
 
-      - name: Build rust code
-        run: cargo build
+  #     - name: Build rust code
+  #       run: cargo build
   
-      - name: Setup Node
-        uses: actions/setup-node@v4
+  #     - name: Setup Node
+  #       uses: actions/setup-node@v4
 
-      - name: Wrangler setup
-        run: npm install -g wrangler
+  #     - name: Wrangler setup
+  #       run: npm install -g wrangler
 
-      - name: Build wasm and deploy
-        env:
-          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
-        run: wrangler deploy --env=prod
+  #     - name: Build wasm and deploy
+  #       env:
+  #         CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
+  #       run: wrangler deploy --env=prod
 
-      - name: Test the build
-        run: |
-          sleep 5
-          curl -s https://id.a1ecbr0wn.com > prod.ip
-          curl -s https://ident.me > idm.ip
-          if ! cmp -s prod.ip idm.ip; then
-            echo "::error title=Deploy Test Failure::IP addresses from id.a1ecbr0wn.com and ident.me do not match"
-            echo "Control Response:"
-            cat idm.ip
-            echo "Prod Response:"
-            cat prod.ip
-            exit 1
-          fi
+  #     - name: Test the build
+  #       run: |
+  #         sleep 5
+  #         curl -s https://id.a1ecbr0wn.com > prod.ip
+  #         curl -s https://ident.me > idm.ip
+  #         if ! cmp -s prod.ip idm.ip; then
+  #           echo "::error title=Deploy Test Failure::IP addresses from id.a1ecbr0wn.com and ident.me do not match"
+  #           echo "Control Response:"
+  #           cat idm.ip
+  #           echo "Prod Response:"
+  #           cat prod.ip
+  #           exit 1
+  #         fi
