Fix to run script

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -83,3 +83,11 @@ jobs:
 
       - name: Build wasm and deploy
         run: CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }} wrangler deploy --env=prod
+
+      - name: Test the build
+        run: |
+          curl -s https://id.a1ecbr0wn.com > prod.ip
+          curl -s https://ident.me > idm.ip
+          if ! cmp -zs prod.ip idm.ip; then
+            echo "::error title=Build Failure::IP addresses do not match"
+          fi
